const products =  [
    {
      _id: "1",
      url: "https://picsum.photos/id/400/800/600",
      name: "Shirt",
      brand: "Nike",
      price: 50,
      stars: 5,
    },
    {
      _id: "2",
      url: "https://picsum.photos/id/401/800/600",
      name: "Slim Shirt",
      brand: "Gap",
      price: 160,
      stars: 4.5,
    },
    {
      _id: "3",
      url: "https://picsum.photos/id/502/800/600",
      name: "Slim Pants",
      brand: "Jackma",
      price: 160,
      stars: 4.0,
    },
    {
      _id: "4",
      url: "https://picsum.photos/id/1010/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
    {
      _id: "5",
      url: "https://picsum.photos/id/1000/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
    {
      _id: "6",
      url: "https://picsum.photos/id/912/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
    {
      _id: "7",
      url: "https://picsum.photos/id/1012/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
    {
      _id: "8",
      url: "https://picsum.photos/800/600",
      name: "Slim Shirt",
      brand: "Nike",
      price: 60,
      stars: 4.5,
    },
  ];

export default products;
